otus_cpp_development_principles: editor.h File Reference
editor.h File Reference
#include <vector>
#include <memory>
Classes
class Figure
class Square
class Circle
class Triangle
class Rectangle
class Tab
class Editor
Functions
template<typename... Args>
void println (std::string format, const Args &... args)
Utility function for printing messages using <fmt> library plus new line character.
Function Documentation
println()
template<typename... Args> void println (std::string format, const Args &... args)
Utility function for printing messages using <fmt> library plus new line character.
Usage: println("Some sentence for formatting {}", "XXX") results to "Some sentence for formatting XXX"
Template Parameters
Args types of parameters for formatting target message
Parameters
format target message for printing
args formatting variables
Definition at line 34 of file editor.cpp.
{
   fmt::print(format, args...);
   std::putc('\n', stdout);
 }
Referenced by Tab::add_figure(), Square::change(), Circle::change(), Triangle::change(), Rectangle::change(), Editor::change_focus_to(), Editor::close_tab(), Editor::create_new_tab(), Editor::Editor(), Editor::open_file(), Tab::remove_figure(), Tab::save(), Editor::start(), and Editor::stop().