otus_cpp_development_principles: editor.cpp File Reference
editor.cpp File Reference
#include <iostream>
#include <vector>
#include "editor.h"
#include <fmt/core.h>
#include <fmt/format.h>
#include <algorithm>
#include <memory>
#include <cstdio>
Macros
#define UNUSED(variable) (void)variable
Functions
template<typename... Args>
void println (std::string format, const Args &... args)
Utility function for printing messages using <fmt> library plus new line character.
Detailed Description
Author
marisarze (you@d.nosp@m.omai.nosp@m.n.com)
Version
0.0.50
Date
Copyright
Copyright (c) 2022
Definition in file editor.cpp.
Macro Definition Documentation
UNUSED
#define UNUSED (variable) (void)variable
Definition at line 22 of file editor.cpp.
Function Documentation
println()
template<typename... Args> void println (std::string format, const Args &... args)
Utility function for printing messages using <fmt> library plus new line character.
Usage: println("Some sentence for formatting {}", "XXX") results to "Some sentence for formatting XXX"
Template Parameters
Args types of parameters for formatting target message
Parameters
format target message for printing
args formatting variables
Definition at line 34 of file editor.cpp.
{
   fmt::print(format, args...);
   std::putc('\n', stdout);
 }
Referenced by Tab::add_figure(), Square::change(), Circle::change(), Triangle::change(), Rectangle::change(), Editor::change_focus_to(), Editor::close_tab(), Editor::create_new_tab(), Editor::Editor(), Editor::open_file(), Tab::remove_figure(), Tab::save(), Editor::start(), and Editor::stop().