otus_cpp_development_principles: Tab Class Reference
Tab Class Reference
#include <editor.h>
Public Member Functions
Tab ()
Construct a new Tab:: Tab object.
Tab (std::string path)
Construct a new Tab:: Tab object from path.
void save (std::string path)
saving Tab to document
void add_figure (std::shared_ptr< Figure > figure)
Method for adding figure to tab content.
void remove_figure (std::shared_ptr< Figure > figure)
Method for removing figure from tab content, if figure is not in content prints corresponding message about nothing to remove.
Public Attributes
std::vector< std::shared_ptr< Figure > > content
Detailed Description
Definition at line 35 of file editor.h.
Constructor & Destructor Documentation
Tab() [1/2]
Tab::Tab ()
Construct a new Tab:: Tab object.
Definition at line 75 of file editor.cpp.
 {}
Tab() [2/2]
Tab::Tab (std::string path)
Construct a new Tab:: Tab object from path.
Parameters
path path for loading tab (new document)
Definition at line 83 of file editor.cpp.
                       {
     UNUSED(path);
 }
References UNUSED.
Member Function Documentation
add_figure()
void Tab::add_figure (std::shared_ptr< Figure > figure)
Method for adding figure to tab content.
Parameters
figure target figure for adding
Definition at line 101 of file editor.cpp.
{
     content.emplace_back(figure);
     println("New figure {} was added to tab {}", fmt::ptr(figure), fmt::ptr(this));
 }
References content, and println().
remove_figure()
void Tab::remove_figure (std::shared_ptr< Figure > figure)
Method for removing figure from tab content, if figure is not in content prints corresponding message about nothing to remove.
Parameters
figure target figure for remove
Definition at line 112 of file editor.cpp.
{
     auto it = std::find(content.begin(), content.end(), figure);
     if (it != content.end()){
         content.erase(it);
         println("Figure {} erased from tab {}", fmt::ptr(figure.get()), fmt::ptr(this));
     } else {
         println("There is nothing to remove from tab {}", fmt::ptr(this));
     }
 }
References content, and println().
save()
void Tab::save (std::string path)
saving Tab to document
Parameters
path path for saving the tab
Definition at line 92 of file editor.cpp.
{
     println("Tab saved to \'{}\'", path);
 }
References println().
Member Data Documentation
content
std::vector<std::shared_ptr<Figure> > Tab::content
Definition at line 37 of file editor.h.
Referenced by add_figure(), and remove_figure().
The documentation for this class was generated from the following files:
editor.h
editor.cpp