otus_cpp_development_principles: Editor Class Reference
Editor Class Reference
#include <editor.h>
Public Member Functions
Editor ()
Construct a new Editor:: Editor object.
void open_file (std::string path)
loading new document to open tabs
void create_new_tab ()
creating new empty tab
void change_focus_to (std::shared_ptr< Tab > tab)
changing focus to target tab through setting "current_tab" parameter value.
void close_tab (std::shared_ptr< Tab > tab)
closing tab (removing it from open tabs).
void start ()
Starting of abstract editor.
void stop ()
Storpping of abstract editor.
Public Attributes
std::vector< std::shared_ptr< Tab > > open_tabs = {}
std::shared_ptr< Tab > current_tab = nullptr
Detailed Description
Definition at line 46 of file editor.h.
Constructor & Destructor Documentation
Editor()
Editor::Editor ()
Construct a new Editor:: Editor object.
Definition at line 126 of file editor.cpp.
               {
     println("Editor created");
 }
References println().
Member Function Documentation
change_focus_to()
void Editor::change_focus_to (std::shared_ptr< Tab > tab)
changing focus to target tab through setting "current_tab" parameter value.
if tab is not among open tabs, then corresponging warning will be prompt.
Parameters
tab Target tab to shift focus.
Definition at line 179 of file editor.cpp.
{
     auto it = std::find(open_tabs.begin(), open_tabs.end(), tab);
     if (it != open_tabs.end()){
         current_tab = tab;
         println("Current focus changed to {}", fmt::ptr(tab.get()));
     } else {
         println("The focus can not be changed to {}", fmt::ptr(tab.get()));
     }
 }
References current_tab, open_tabs, and println().
Referenced by close_tab(), create_new_tab(), and open_file().
close_tab()
void Editor::close_tab (std::shared_ptr< Tab > tab)
closing tab (removing it from open tabs).
If the tab does not exist among the open ones, then displays the appropriate message.
Parameters
tab target tab for closing
Definition at line 159 of file editor.cpp.
{
     auto it = std::find(open_tabs.begin(), open_tabs.end(), tab);
     if (it != open_tabs.end()){
         open_tabs.erase(it);
         println("Tab {} erased from the editor", fmt::ptr(tab.get()));
         if ((int)open_tabs.size()>0){
             change_focus_to(open_tabs[0]);
         } else {
             current_tab = nullptr;
         }
     } else {
         println("Target tab {} is not exist among open tabs", fmt::ptr(tab.get()));
     }
 }
References change_focus_to(), current_tab, open_tabs, and println().
create_new_tab()
void Editor::create_new_tab ()
creating new empty tab
Definition at line 146 of file editor.cpp.
{
     auto new_tab = std::make_shared<Tab>();
     open_tabs.emplace_back(new_tab);
     println("New empty tab {} created", fmt::ptr(new_tab.get()));
     change_focus_to(new_tab);
 }
References change_focus_to(), open_tabs, and println().
open_file()
void Editor::open_file (std::string path)
loading new document to open tabs
Parameters
path path for loading new tab
Definition at line 135 of file editor.cpp.
{
     auto new_tab = std::make_shared<Tab>(path);
     open_tabs.emplace_back(new_tab);
     println("New empty tab {} created with loading from \'{}\'", fmt::ptr(new_tab.get()), path);
     change_focus_to(new_tab);
 }
References change_focus_to(), open_tabs, and println().
start()
void Editor::start ()
Starting of abstract editor.
Definition at line 193 of file editor.cpp.
                   {
     println("Starting the engine");
 }
References println().
stop()
void Editor::stop ()
Storpping of abstract editor.
Definition at line 201 of file editor.cpp.
                  {
     println("Preparing for stopping the engine...Stopped");
 }
References println().
Member Data Documentation
current_tab
std::shared_ptr<Tab> Editor::current_tab = nullptr
Definition at line 49 of file editor.h.
Referenced by change_focus_to(), and close_tab().
open_tabs
std::vector<std::shared_ptr<Tab> > Editor::open_tabs = {}
Definition at line 48 of file editor.h.
Referenced by change_focus_to(), close_tab(), create_new_tab(), and open_file().
The documentation for this class was generated from the following files:
editor.h
editor.cpp